name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set tag as env
        run: echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Build
        run: echo $VERSION > Release.txt
      - name: Install xmllint
        run: sudo apt-get install -y dh-make devscripts
      - name: deb build
        run: |
          cd scripts
          mkdir pq-app-$VERSION
          cd pq-app-$VERSION
          cp ../*.sh .
          dh_make --indep --createorig -y
          echo "*.sh usr/bin" > debian/install
          debuild -us -uc
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release.txt
            scripts/*.deb
